name = "RoMatch"
author = "Dog2puppy"
license = "Mozilla Public License Version 2.0"
content_root = "src"
version = "0.1.0"

[dependencies]
t = { git = "https://github.com/osyrisrblx/t", rev = "master" }